CREATE TABLE IF NOT EXISTS User (
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(70),
	email VARCHAR(70) NOT NULL,
	name VARCHAR(200),
	about TEXT,
	isAnonymous TINYINT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY(email),
	UNIQUE KEY id_unique (id)
	)
	ENGINE=InnoDB
	DEFAULT CHARACTER SET='utf8';

CREATE TABLE IF NOT EXISTS Forum (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	short_name VARCHAR(150) NOT NULL,
	user VARCHAR(70) NOT NULL,
	PRIMARY KEY(short_name),
	UNIQUE KEY uniqIdx_id(id),
	UNIQUE KEY(name),
	FOREIGN KEY(user) REFERENCES User(email) ON UPDATE CASCADE ON DELETE NO ACTION
	)
	ENGINE=InnoDB
	DEFAULT CHARACTER SET = 'utf8';

CREATE TABLE IF NOT EXISTS Thread (
	id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	slug VARCHAR(150) NOT NULL,
	message TEXT NOT NULL,
	likes INT NOT NULL DEFAULT '0',
	dislikes INT NOT NULL DEFAULT '0',
	isClosed TINYINT(1) NOT NULL DEFAULT '0',
	isDeleted TINYINT(1) NOT NULL DEFAULT '0',
	date D	ATETIME NOT NULL,
	forum VARCHAR(150) NOT NULL,
	user VARCHAR(70) NOT NULL,
	posts INT NOT NULL DEFAULT '0',
	PRIMARY KEY(id),
	FOREIGN KEY(forum) REFERENCES Forum(short_name) ON UPDATE CASCADE ON DELETE NO ACTION,
	FOREIGN KEY(user) REFERENCES User(email) ON UPDATE CASCADE ON DELETE NO ACTION
	)
	ENGINE=InnoDB
	DEFAULT CHARACTER SET = 'utf8';

CREATE TABLE IF NOT EXISTS Post (
	id INT NOT NULL AUTO_INCREMENT,
	message TEXT NOT NULL,
	likes INT NOT NULL DEFAULT '0',
	dislikes INT NOT NULL DEFAULT '0',
	isApproved TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Утвержденный',
	isDeleted TINYINT(1) NOT NULL DEFAULT '0',
	isEdited TINYINT(1) NOT NULL DEFAULT '0',
	isHighlighted TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Подсвеченный',
	isSpam TINYINT(1) NOT NULL DEFAULT '0',
	date DATETIME NOT NULL,
	parent INT DEFAULT NULL,
	forum VARCHAR(150) NOT NULL,
	thread INT NOT NULL,
	user VARCHAR(70) NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(forum) REFERENCES Forum(short_name) ON UPDATE CASCADE ON DELETE NO ACTION,
	FOREIGN KEY(thread) REFERENCES Thread(id) ON UPDATE CASCADE ON DELETE NO ACTION,
	FOREIGN KEY(user) REFERENCES User(email) ON UPDATE CASCADE ON DELETE NO ACTION
	)
	ENGINE=InnoDB
	DEFAULT CHARACTER SET = 'utf8';


CREATE TABLE IF NOT EXISTS Followers (
	follower VARCHAR(70) NOT NULL,
	followee VARCHAR(70) NOT NULL,
	FOREIGN KEY(follower) REFERENCES User(email) ON UPDATE CASCADE ON DELETE NO ACTION,
	FOREIGN KEY(followee) REFERENCES User(email) ON UPDATE CASCADE ON DELETE NO ACTION
	)
	ENGINE=InnoDB
	DEFAULT CHARACTER SET = 'utf8';

CREATE TABLE IF NOT EXISTS Subscriptions (
	user VARCHAR(70) NOT NULL,
	thread INT NOT NULL COMMENT 'id thread-а, на который подписан user',
	CONSTRAINT FOREIGN KEY(user) REFERENCES User(email)  ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT FOREIGN KEY(thread) REFERENCES Thread(id) ON UPDATE CASCADE ON DELETE NO ACTION
	)
	ENGINE=InnoDB
	DEFAULT CHARACTER SET='utf8';


-- DROP ALL TABLES
DROP TABLE IF EXISTS Followers;
DROP TABLE IF EXISTS Subscriptions;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Thread;
DROP TABLE IF EXISTS Forum;
DROP TABLE IF EXISTS User;


-- CREATE INDEXES
CREATE INDEX index_name ON User(name);
CREATE INDEX idxThr_usr_date ON Thread(user, date);
CREATE INDEX idxThr_forum_date ON Thread(forum, date);
CREATE INDEX idxP_usr_date ON Post(user, date);
CREATE INDEX idxP_forum_date ON Post(forum, date);
CREATE INDEX idxP_thr_date ON Post(thread, date);
CREATE INDEX Idx_usr_thr ON Post(user, thread);
CREATE UNIQUE INDEX iniqIdx_fer_fee ON Followers(follower, followee);
CREATE UNIQUE INDEX uniqIdx_fee_fer ON Followers(followee, follower);